site_name: Open Autonomy Framework
site_url: https://docs.autonolas.network/
site_description: Documentation for the Open Autonomy Framework
site_author: Valory AG
copyright: Valory AG 2021-2023

repo_name: valory-xyz/open-autonomy
repo_url: https://github.com/valory-xyz/open-autonomy
edit_uri: ""

nav:
  - Get Started:
    - What is an agent service?: 'get_started/what_is_an_agent_service.md'
    - Why do we need agent services?: 'get_started/why_do_we_need_agent_services.md'
    - Use cases: 'get_started/use_cases.md'
    - Agent services compared to: 'get_started/agent_services_compared_to.md'
  - Guides:
    - Overview: 'guides/index.md'
    - Quick start: 'guides/quick_start.md'
    - Set up: 'guides/set_up.md'
    - Overview of the development process: 'guides/overview_of_the_development_process.md'
    - Draft service idea and define FSM specification: 'guides/draft_service_idea_and_define_fsm_specification.md'
    - Define agent: 'guides/define_agent.md'
    - Code FSM app skill: 'guides/code_fsm_app_skill.md'
    - Define service: 'guides/define_service.md'
    - Deploy service: 'guides/deploy_service.md'
    - Publish and fetch packages: 'guides/publish_fetch_packages.md'
    - Publish and mint packages: 'guides/publish_mint_packages.md'
    - Bumping services: 'guides/bumping_services.md'
  - Key Concepts:
    - Overview: 'key_concepts/index.md'
    - AEA: 'key_concepts/aea.md'
    - FSM:
      - Overview: 'key_concepts/fsm.md'
      - FSM App:
        - Introduction: 'key_concepts/fsm_app_introduction.md'
        - Components: 'key_concepts/fsm_app_components.md'
    - ABCI:
      - Overview: 'key_concepts/abci.md'
      - ABCI App:
        - Class: 'key_concepts/abci_app_class.md'
        - Abstract Round: 'key_concepts/abci_app_abstract_round.md'
        - Abstract Round Behaviour: 'key_concepts/abci_app_abstract_round_behaviour.md'
        - Async Behaviour: 'key_concepts/abci_app_async_behaviour.md'
      - Implementation:
        - Component Interactions: 'key_concepts/abci_app_interactions.md'
        - Sequence Diagrams: 'key_concepts/poc-diagram.md'
    - Security:
      - Threat Model: 'key_concepts/threat_model.md'
  - Configure the service:
    - The service configuration file: 'configure_service/service_configuration_file.md'
    - Configure access to external chains: 'configure_service/configure_access_external_chains.md'
    - On-chain deployment checklist: 'configure_service/on-chain_deployment_checklist.md'
    - Analyze and test: 'configure_service/analyze_test.md'
  - Developer Tools:
    - Overview: 'advanced_reference/index.md'
    - Local Development:
      - Dev Mode: 'advanced_reference/developer_tooling/dev_mode.md'
      - Execution Replay: 'advanced_reference/developer_tooling/execution_replay.md'
      - Benchmarking: 'advanced_reference/developer_tooling/benchmarking.md'
    - Debugging:
      - Cluster Debugging: 'advanced_reference/developer_tooling/debugging_in_the_cluster.md'
      - Tenderly Integration: 'advanced_reference/developer_tooling/debugging_using_tenderly.md'
    - CLI Commands:
      - Fetch Service Files: 'advanced_reference/commands/autonomy_fetch_service_files.md'
      - Kubernetes Deployment: 'advanced_reference/commands/autonomy_kubernetes_deployment.md'
    - Deployment:
      - Container Control Flow: 'control_flow.md'
      - Custom Images: 'advanced_reference/use_custom_images.md'
      - Custom Dockerfile: 'advanced_reference/developer_tooling/custom_agent_image.md'
      - On-Chain Addresses: 'advanced_reference/on_chain_addresses.md'
  - API Reference:
    - Core Library:
      - Constants: 'api/constants.md'
      - Analysis Tools:
        - ABCI:
          - App Spec: 'api/analyse/abci/app_spec.md'
          - Docstrings: 'api/analyse/abci/docstrings.md'
          - Handlers: 'api/analyse/handlers.md'
          - Logs:
            - Base: 'api/analyse/logs/base.md'
            - Collection: 'api/analyse/logs/collection.md'
            - Db: 'api/analyse/logs/db.md'
        - Benchmark:
          - Aggregate: 'api/analyse/benchmark/aggregate.md'
          - HTML: 'api/analyse/benchmark/html.md'
        - CLI: 
          - Analyse: 'api/cli/analyse.md'
          - Core: 'api/cli/core.md'
          - Deploy: 'api/cli/deploy.md'
          - Develop: 'api/cli/develop.md'
          - Fetch: 'api/cli/fetch.md'
          - Hash: 'api/cli/hash.md'
          - Publish: 'api/cli/publish.md'
          - Push All: 'api/cli/push_all.md'
          - Replay: 'api/cli/replay.md'
          - Utils: 'api/cli/utils/click_utils.md'
          - Build Images: 'api/cli/build_images.md'
          - Scaffold FSM: 'api/cli/scaffold_fsm.md'
          - Helpers:
            - Deployment: api/cli/helpers/deployment.md
            - Docstring: api/cli/helpers/docstring.md
            - FSM Spec: api/cli/helpers/fsm_spec.md
            - IFPS Hash: api/cli/helpers/ipfs_hash.md
            - Registry: api/cli/helpers/registry.md
        - Configurations:
          - Base: 'api/configurations/base.md'
          - Constants: 'api/configurations/constants.md'
          - Loader: 'api/configurations/loader.md'
          - Validation: 'api/configurations/validation.md'
        - Deploy:
          - Base: 'api/deploy/base.md'
          - Build: 'api/deploy/build.md'
          - Constants: 'api/deploy/constants.md'
          - Image: 'api/deploy/image.md'
          - Generators:
            - Docker Compose:
              - Base: 'api/deploy/generators/docker_compose/base.md'
              - Templates: 'api/deploy/generators/docker_compose/templates.md'
            - Kubernetes:
              - Base: 'api/deploy/generators/kubernetes/base.md'
              - Templates: 'api/deploy/generators/kubernetes/templates.md'
        - Replay:
          - Agent: 'api/replay/agent.md'
          - Tendermint: 'api/replay/tendermint.md'
          - Utils: 'api/replay/utils.md'
        - FSM:
          - Scaffold:
            - Constants: api/fsm/scaffold/constants.md
            - Base: api/fsm/scaffold/base.md
            - Scaffold tools: api/fsm/scaffold/scaffold_skill.md
            - Generators:
              - Components: api/fsm/scaffold/generators/components.md
              - Tests: api/fsm/scaffold/generators/tests.md
            - Templates:
              - Components: api/fsm/scaffold/templates/components.md
              - Tests: api/fsm/scaffold/templates/tests.md
        - Test Tools:
          - Configurations: 'api/plugins/aea_test_autonomy/configurations.md'
          - Fixture Helpers: 'api/plugins/aea_test_autonomy/fixture_helpers.md'
          - Base Test Classes:
            - Agents: 'api/plugins/aea_test_autonomy/base_test_classes/agents.md'
            - Contracts: 'api/plugins/aea_test_autonomy/base_test_classes/contracts.md'
          - Docker:
            - ACN Node: 'api/plugins/aea_test_autonomy/docker/acn_node.md'
            - AMM Net: 'api/plugins/aea_test_autonomy/docker/amm_net.md'
            - Base: 'api/plugins/aea_test_autonomy/docker/base.md'
            - Ganache Helpers: 'api/plugins/aea_test_autonomy/docker/ganache.md'
            - Gnosis Safe Helpers: 'api/plugins/aea_test_autonomy/docker/gnosis_safe_net.md'
            - Registries: 'api/plugins/aea_test_autonomy/docker/registries.md'
            - Tendermint Helpers: 'api/plugins/aea_test_autonomy/docker/tendermint.md'
          - Helpers:
            - Async Utils: 'api/plugins/aea_test_autonomy/helpers/async_utils.md'
            - Base: 'api/plugins/aea_test_autonomy/helpers/base.md'
            - Contracts: 'api/plugins/aea_test_autonomy/helpers/contracts.md'
            - Tendermint Utils: 'api/plugins/aea_test_autonomy/helpers/tendermint_utils.md'
      - Connections:
        - ABCI:
          - Check Dependencies: 'api/connections/abci/check_dependencies.md'
          - Connection: 'api/connections/abci/connection.md'
          - Dialogues: 'api/connections/abci/dialogues.md'
          - Tendermint Decoder: 'api/connections/abci/tendermint_decoder.md'
          - Tendermint Encoder: 'api/connections/abci/tendermint_encoder.md'
          - Scripts: 'api/connections/abci/scripts/genproto.md'
      - Contracts:
        - Gnosis Safe:
          - Contract: 'api/contracts/gnosis_safe/contract.md'
      - Protocols:
        - ABCI:
          - Message: 'api/protocols/abci/message.md'
          - Dialogues: 'api/protocols/abci/dialogues.md'
          - Custom Types: 'api/protocols/abci/custom_types.md'
      - Skills:
        - Abstract Round ABCI:
          - Base: 'api/skills/abstract_round_abci/base.md'
          - Behaviours: 'api/skills/abstract_round_abci/behaviours.md'
          - Handlers: 'api/skills/abstract_round_abci/handlers.md'
          - Models: 'api/skills/abstract_round_abci/models.md'
        - Registration ABCI:
          - Behaviours: 'api/skills/registration_abci/behaviours.md'
          - Handlers: 'api/skills/registration_abci/handlers.md'
          - Models: 'api/skills/registration_abci/models.md'
          - Payloads: 'api/skills/registration_abci/payloads.md'
  - CLI Guide:
    - Overview: 'cli_overview.md'
    - Core Commands:
      - autonomy analyse: 'advanced_reference/commands/autonomy_analyse.md'
      - autonomy build-image: 'advanced_reference/commands/autonomy_build-image.md'
      - autonomy deploy: 'advanced_reference/commands/autonomy_deploy.md'
      - autonomy fetch: 'advanced_reference/commands/autonomy_fetch.md'
      - autonomy hash: 'advanced_reference/commands/autonomy_hash.md'
      - autonomy mint: 'advanced_reference/commands/autonomy_mint.md'
      - autonomy publish: 'advanced_reference/commands/autonomy_publish.md'
      - autonomy push-all: 'advanced_reference/commands/autonomy_push_all.md'
      - autonomy scaffold: 'advanced_reference/commands/autonomy_scaffold.md'
      - autonomy service: 'advanced_reference/commands/autonomy_service.md'
      - autonomy fetch service-files: 'advanced_reference/commands/autonomy_fetch_service_files.md'
      - autonomy kubernetes-deployment: 'advanced_reference/commands/autonomy_kubernetes_deployment.md'
    - Development Commands:
      - autonomy develop: 'advanced_reference/commands/autonomy_develop.md'
      - autonomy replay: 'advanced_reference/commands/autonomy_replay.md'
  - Questions and Answers: 'questions-and-answers.md'
  - Application Deployment: 'application_deployment.md'
  - Counter Example: 'counter_example.md'
  - Upgrading: 'upgrading.md'

theme:
  name: material
  # Temporarily commenting out custom theme for testing
  # custom_dir: docs/custom_theme
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

plugins:
  - search
  - macros
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: true
            docstring_style: google

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/valory-xyz
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/autonolas
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/z2PT65jKqQ

extra_css:
  - stylesheets/extra.css
