name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: actions/configure-pages@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          pip install mkdocstrings[python]
          pip install mkdocs-include-markdown-plugin
          pip install mkdocs-macros-plugin
      - name: Install package
        run: pip install -e .
      - name: Build site
        run: mkdocs build
        env:
          PYTHONPATH: ${{ github.workspace }}
      - name: Verify build output
        run: |
          if [ ! -d "site" ]; then
            echo "Documentation build failed - site directory not created"
            exit 1
          fi
          echo "Documentation build successful - site directory created and contains:"
          ls -la site/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
