name: Test Documentation Build

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          pip install mkdocstrings[python]
          pip install mkdocs-include-markdown-plugin
      - name: Install package
        run: pip install -e .
      - name: Build site
        run: mkdocs build
        env:
          PYTHONPATH: ${{ github.workspace }}
      - name: Verify build output
        run: |
          if [ ! -d "site" ]; then
            echo "Documentation build failed - site directory not created"
            exit 1
          fi
          echo "Documentation build successful - site directory created and contains:"
          ls -la site/
